### ISSUE TITLE
issue in fetching data in python - Status error: 2

### ISSUE THREAD

**Issue by himanshudhingra** [damnee562/redash-api-client#1]
Hi,
I am using Redash.generate_query_result to fetch data from Redash. 
It behaves randomly that sometimes it gets the result and sometimes throws an error with Status: 2. Attaching screenshot.

![image](https://user-images.githubusercontent.com/9049212/53319059-6ee3a100-38f7-11e9-90b5-e682d418beee.png)

The same query runs in Redash successfully hence, no issues with server. 

Currently using Python's Try, Exception to complete the job, but it sometimes take forever to execute.
Is it a known issue? What can be the possible reasons for it and what can be the solution?

**Comment by damienzeng73** [comment]
Hi, himanshudhingra

Status: 2 means **processing**.

You can find all statuses here
https://github.com/getredash/redash/blob/8f0cffe42494b603b4c8f5c7c65cfce7ccf93d64/client/app/services/query-result.js#L56-L61

If you want to fetch data, you should use `Redash.get('query_results/{query_result_id}')` instead.
