### ISSUE TITLE
x and y axis error with some type of visualization

### ISSUE THREAD

**Issue by Scartiloffista** [damnee562/redash-api-client#8]
When using create_visualizations() with some kind of visualizations type (eg: counter, funnel, etc), the API gives errors regarding x and y axis, even when they are not supposed to be given for that kind of visualizations.

**Comment by damienzeng73** [comment]
This package is only support the following types of visualization right now:
`table`, `line`, `column`, `area`, `pie`, `scatter`, `bubble`, `box`, `pivot`

Maybe we should raise some exception when user pass any unsupported types.

**Comment by damienzeng73** [comment]
> This package is only support the following types of visualization right now:
> `table`, `line`, `column`, `area`, `pie`, `scatter`, `bubble`, `box`, `pivot`
> 
> Maybe we should raise some exception when user pass any unsupported types.

Added in https://github.com/damnee562/redash-api-client/commit/181d42ebbaef7133cce36c5e14d3208351064a09 .
